### ISSUE TITLE
blog post for 0.19.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAnalysis.github.io#94]
The 0.19.0 release (https://github.com/MDAnalysis/mdanalysis/issues/1971) is imminent (PR https://github.com/MDAnalysis/mdanalysis/pull/2095) so we need a blog post that summarizes the major things.

- [ ] Windows conda packages (Python 3 only)
- [ ] contributions from GSoC (we want the separate posts #87 and #90 up as soon as possible, too, so that we can link to them; I would prefer them to come *before* the release post)
   - [ ] distances and PBC handling 
          – link to #90 
          - *periodic* keyword for `select_atoms()`
   - [ ] on-the-fly transformations – link to #87 
- [ ] contributions from NSF REU (dihedral and Ramachandran/Janin analysis – can use something from [Henry's bio page](https://becksteinlab.physics.asu.edu/people/118/henry-mull))
- [ ] various performance improvements (see CHANGELOG)
- [ ] ChainReader can now smartly concatenate trajectories and drop duplicated frames
- [ ] sliced trajectory objects
- [ ] improvements/additions in analysis
  - [ ] density (more flexibility in choosing the analyzed volume)
  - [ ] radial distribution function (InterRDF_s)
- [ ] formats
  - [ ] added hybrid36 format for PDB-like files
  - [ ] SETTLE constraints in Gromacs TPR files are now read as bonds (MDAnalysis/mdanalysis#1949)
  - [ ] MemoryReader is now feature-complete: supports box size and the new transformations; various inconsistencies fixed. Basic idea: any changes to the MemoryReader's data (positions, velocities, forces, dimensions) are permanent.
- [ ] deprecations
  - [ ] removed `quiet=True`; use `verbose=False` instead
  - [ ] analysis: use `run(start, stop, step)`
  - [ ] save data using your own tools instead of `.save()` methods: easier to maintain because formats change (e.g. pickle) and we think the user knows best how they want to keep their data
 - [x] deprecated "flags" (probably no-one used them... MDAnalysis/mdanalysis#782 for details)
- [x] highlight new contributors

**Comment by richardjgowers** [comment]
Yeah it would be good to get the two gsoc posts finally finished, I'm behind on that

**Comment by orbeckst** [comment]
In discussion with @davidercruz on PR #87 it became clear that some of the crucial features for on-the-fly transformations are not in 0.19.0 yet but are still PRs
- wrap/unwrap  PR https://github.com/MDAnalysis/mdanalysis/pull/2038
- fitting transformations PR https://github.com/MDAnalysis/mdanalysis/pull/1991
- centering PR https://github.com/MDAnalysis/mdanalysis/pull/1973

@davidercruz rightly pointed out https://github.com/MDAnalysis/MDAnalysis.github.io/pull/87#issuecomment-429227455 that announcing OTFT without these features makes it much less exciting (and robs it of impact).

My suggestion for the 0.19.0 blog post is https://github.com/MDAnalysis/MDAnalysis.github.io/pull/87#issuecomment-429236926 to only briefly mention the transformations along the lines that we outline the idea, state that the foundations are implemented, it's experimental, and cool things are coming. 

The OTFT blog post #86 (PR #87) will then be published *after* the 0.19.0 release announcement and we try to get the OTFO PRs done for a 0.20.0 (or 1.0.0?) release. (We cannot put them in a 0.19.1 because they are new features and those cannot go into a patch release under semantic versioning.)

What are your opinions, especially @davidercruz @jbarnoud @richardjgowers  ?

**Comment by jbarnoud** [comment]
Sorry, These PRs are hanging by my fault. The wrap/unwrap is basically ready. I would need to run it on a couple of systems to make sure I did not miss anything obvious but I can do that latter today. The two other PRs need a bit more testing on my part as they are doing less obvious things.

**Comment by davidercruz** [comment]
The PRs are really close to completion, so, unless some nasty bugs are found, we can try to push OTFT for the 0.19.0 release. @jbarnoud what do you think?

**Comment by richardjgowers** [comment]
@davidercruz 0.19 is out already. 

We can wait and make sure all these PRs are 100% finished and make 0.20.0 the big transformations release.  It won't be another 6 months before a release this time, I'm working on making the process easier

**Comment by orbeckst** [comment]
@richardjgowers we should get this blog post updated for 0.19.x (Windows!) and then do an announcement on twitter, too.
